#!/bin/sh -e

PROJECT=snomed-release
ARTIFACT=api
NAME=${PROJECT}-${ARTIFACT}

mkdir -p /var/run/snomed-release-api
chmod 700 /var/run/snomed-release-api

if ! getent passwd snomed-release-api >/dev/null; then
  adduser --quiet --system --no-create-home --home /opt/${PROJECT} --shell /bin/false ${NAME}
fi

mkdir -p /var/run/snomed-release-api
mkdir -p /var/lib/snomed-release-api
chmod 700 /var/run/snomed-release-api
chmod 700 /var/lib/snomed-release-api
chown snomed-release-api /var/run/snomed-release-api
chown snomed-release-api /var/lib/snomed-release-api

start snomed-release-api
