#!/bin/sh -e

APP_NAME=[[packageName]]

case $1 in
	purge)
		if getent passwd $APP_NAME >/dev/null; then
  			userdel $APP_NAME
		fi
		if test -d /var/lib/$APP_NAME; then
			rm -r /var/lib/$APP_NAME
		fi
	;;
esac
