#!/bin/sh -e

PROJECT=snomed-release
ARTIFACT=api
NAME=${PROJECT}-${ARTIFACT}

if ! getent passwd snomed-release-api >/dev/null; then
  adduser --quiet --system --no-create-home --home /opt/${PROJECT} --shell /usr/sbin/nologin ${NAME}
fi

chown ${NAME} /var/run/${NAME}
chmod 700 /var/run/${NAME}
