#!/bin/sh -e

#For debugging uncomment these two lines
set -x
echo $*

APP_NAME=[[packageName]]

# Record package version number
echo [[version]] > /var/opt/snomed-release-service-api/version.txt

supervisorctl update $APP_NAME || true
supervisorctl start $APP_NAME || true
