#!/bin/sh -e

#For debugging uncomment these two lines
#set -x
#echo $*

APP_NAME=[[packageName]]

if ! getent group $APP_NAME> /dev/null
then
  addgroup --quiet --system $APP_NAME
fi

if ! getent passwd $APP_NAME >/dev/null; then
  adduser --quiet --system --no-create-home --group $APP_NAME \
    --home /var/opt/$APP_NAME --shell /bin/false $APP_NAME
fi
